# Generated by Django 4.1.1 on 2023-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='pic1'),
        ),
    ]
